### PR TITLE
Clustering itests

### PR DESCRIPTION
**Pull request by tsegismont**
Please do not merge yet.

Sharing to gather feedback early.

### CODE REVIEW

**Comment by cescoffier** [comment]
I've built an example using the same approach but using the Fabric8 Maven Plugin & S2I (instead of docker file): https://github.com/cescoffier/vertx-openshift-cluster-examples/tree/master/eventbus-example

**Comment by tsegismont** [comment]
@cescoffier can you have a quick look? I updated the FMP config as advised. There's a bunch of files but most of them are Openshift templates for the FMP.

Once this is merged I'll push to master again (now I'm confident with the test infra)

**Comment by cescoffier** [comment]
@tsegismont that's awesome! It looks good to me (in term of infra and tests).

**Comment by tsegismont** [comment]
@cescoffier thanks for the review!

**Pull request merged**
